### ISSUE TITLE
tfsandbox not being able to create a window for itself

### ISSUE THREAD

**Issue by gahabana** [stengerh/foo_tfsandbox#5]
hi, i tried tfsandbox under Wine both on MacOs as well as Ubuntu Linux 16.04 with 1.98 as well as 2.0rc3 Wine code.
However I try - sanbox windows never shows up and in Console log file i see a message"
`foo_tfsandbox: Could not create window: Success.  `

Is there a workaround or some other component that might be causing the problem ?

thanks in advance !

**Comment by stengerh** [comment]
I suspect the Scintilla editor widget was not registered correctly. I can reproduce the symptom on Windows if I remove or rename SciLexer.dll. How did you install the component?

**Comment by gahabana** [comment]
hi, I installed it via foobar2000's install-extensions panel.
Is there another way how I could register the component and/or SciLexer.dll ?
I installed foobar in 'portable' mode so all data is in foobar's directory.
subdirectory 'user-components' has among others sub-directory 'foo_tfsandbox' which contains these 3 files:
`
foo_tfsandbox.dll
LexTitleformat.dll
SciLexer.dll
`
thanks for the advice !

**Comment by gahabana** [comment]
solution found - tried to copy SciLexer.dll into  windows/system32 but did not work but when copied into windows/syswow64 subdirectory it works :)
so solution is to copy it from 
> foobar2000/user-components/foo_tfsandbox
> to
> ~/.wine/drive_c/windows/syswow64/

**Comment by stengerh** [comment]
I'm glad you could solve this. If the syntax highlighting does not work you may have to do the same for LexTitleformat.dll.

foo_fsandbox loads these two DLLs as [side-by-side assemblies](https://msdn.microsoft.com/en-us/library/dd408052(v=vs.85).aspx). I think the most likely reason for your problem is that your version of Wine does not fully implement this feature (or I made some minor mistake in the side-by-side manifests which Microsoft Windows does not mind).

If you want to keep the syswow64 directory clean you could put these two DLLs into the foobar2000 installation directory, i.e. in the same directory as foobar2000.exe.
